BEGIN TRANSACTION;
CREATE VIRTUAL TABLE Downloads_fts_idx USING fts5(
              title, reddit_title, content='Downloads', content_rowid='id');
CREATE TABLE "Downloads"(
    id INTEGER PRIMARY KEY ASC,
    date TEXT,
    time TEXT,
    description TEXT,
    local_filename TEXT,
    title TEXT,
    url_file TEXT,
    url TEXT,
    created_utc REAL,
    r_post_url TEXT,
    reddit_id TEXT,
    reddit_title TEXT,
    reddit_url TEXT,
    reddit_user TEXT,
    sgasm_user TEXT,
    subreddit_name TEXT, rating REAL, favorite INTEGER DEFAULT 0 NOT NULL);
INSERT INTO "Downloads_fts_idx" VALUES ('[F4M] A Paradise Flight','[F4M] A Paradise Flight [Flight Attendant][Freeuse][Creampie][Blowjob][Cock Worship][Wet Sounds][Binaural]'),
 ('Do your duty as member of this house, little brother, and give me an heiress...','[F4M] Do your duty as member of this house, little brother, and give me an heiress... [D&D setting] [Drow Politics] [Incest] [Brother/Sister] [ADULTS] [FDom] [Whispers] [Manipulation] thus [RAPE] [Breeding] [Riding you] [Creampie] [You''re the only one worthy] [So fill my up womb]] [Accent]'),
 ('[F4M] The world on my shoulders [Script Fill] [Single mom] [Stressed] [Imposter syndrome] [Tears] [Comforting] [Hold the Moan] [Cunnilingus] [Blowjob] Gentle and Sloppy [Facefucking] [Doggy] [Cum inside me] [Co-workers to lovers] [Vanilla] [27:12]','[F4M] The world on my shoulders [Script Fill] [Single mom] [Stressed] [Imposter syndrome] [Tears] [Comforting] [Kid in the next room] [Hold the Moan] [Cunnilingus] [Blowjob] Gentle and Sloppy [Facefucking] [Doggy] [Cum inside me] [Co-workers to lovers] [Vanilla] [27:12]'),
 ('[F4M] Bikini Car Wash [Script Fill] [Strangers to Lovers] [Striptease] [Bikini] [Missionary] [Doggystyle] [Creampie] [Promo Girl] [Sir] [Sweet Tease]','[F4M] Bikini Car Wash: We clean your ride then ride you! [Script Fill] [Strangers to Lovers] [Striptease] [Bikini] [Missionary] [Doggystyle] [Creampie] [Promo Girl] [Sir] [Sweet] and [Playful] with a little [Slap] when you get hand-sy too early'),
 ('Taken Care of By A Cowgirl Succubus (18+)','[F4M] Cow Girl Succubus Breastfeeds and Comforts You [Gentle Fdom] [Aphrodisiac] [Breast Milk] [Nursing Handjob] [Shy to Bold] [Monster Girl] [Face Sitting] [Oral] [Reassurance] [Positivity] [Kindness] [Nerdy, Lonely Girl] [Lactation] [Cum Noises] [Big Boobs] [Hair Pulling] [Doggy Style][Corruption]'),
 ('[F4M] Maid Helps You Out [Freeuse] [Blowjob] [Cock Kisses] [Begging] [Kissing] [Thigh Kisses] [Use Me For Your Pleasure] [I Want To Milk Your Cum Out] [L-bombs] [Creampie]','[F4M] Maid Helps You Out [Freeuse] [Blowjob] [Cock Kisses] [Begging] [Kissing] [Thigh Kisses] [Use Me For Your Pleasure] [I Want To Milk Your Cum Out] [L-bombs] [Creampie]'),
 ('Tomboy Lifeguard saves your life','[F4M] Tomboy Lifeguard saves her best friend''s life, and now she wants to show him how much she cares [Friends to Lovers] [Beach] [Saving his life] [Blowjob] [Cowgirl] [Doggy] [Spanking] [Creampie]'),
 ('[F4M] In the arms of a cheshire cat [monster girl] Script Fill','[Script Fill ][F4M] In the arms of a cheshire cat [monster girl][monstergirl][cheshire cat][bully to lover][childhood friend]?[cuddles][kissing][part narrative][ear licking][L-bomb][good boy][aftercare][comforting you][gentle Fdom][had a crush on you the whole time][slight stalker][wholesome]'),
 ('lunarhiccups | jackoff fantasy','[f4m] [script fill]] i want to be more than just a jack-off fantasy [tight dress teasing] [vanilla Fsub][creampie] [fantasies & dirty talk] [do whatever you want to me] [i''m here with my legs spread, whenever you need it. i''m your porn star] [soft voice] [whispers] [asmr]'),
 ('Taking Your Slave Princess’s Virginity','[F4M] Taking Your Slave Princess’s Virginity [Script Fill] [Slavegirl] [Kidnapped] [Innocence] [Prepared & Perfumed for You] [Rape] [Pleading] [Pinned Wrists] [Helpless][Forced Kissing] [Squirming] [Creampie] [Soft Tears][Virgin’s Blood][Primal] [Body Betrayal] [I''ll Be a Good Girl] [Performed LIVE]'),
 ('[F4M] Fleshlight fun with your dominant girlfriend','[F4M] Fleshlight fun with your dominant, teasing girlfriend [gentle femdom] [fleshlight] [teasing] [making you fuck your toy while i watch] [have you earned the right to fuck me?] [good boy] [creampie] [breeding]'),
 ('[F4A] Late Night Whispers [ASMR][Whispers][Ear licking][Kissing][Moaning][Teasing][O Control][Gentle Femdom][Good Slut][Hypnotic]','[F4A] Late Night Whispers [ASMR][Whispers][Ear licking][Kissing][Moaning][Teasing][O Control][Gentle Femdom][Good Slut][Hypnotic][15:52]'),
 ('[F4M] [Script Fill] Your friend’s mom [Gentle Fdom] [MILF] [Massage] [Flirting] [Teasing] [Dirty talk] [Handjob] [Lube] [Titjob] [Blowjob] [CIM] [Swallowing cum] [good boys]','[F4M] [Script fill] Your friend’s gorgeous mom knows you’ve been stressed - and relieves you in every way you need. [Gentle Fdom] [MILF] [Massage] [Flirting] [Teasing] [Dirty talk] [Handjob] [Lube] [Titjob] [Blowjob] [Sucking your stress away] [Cum in my mouth] [Swallowing cum] [LOTS of good boys]'),
 ('Your Future Girlfriend Wants to Fuck Your Brains Out','[F4M] Your future girlfriend wants to fuck your brains out [Script Fill] [GFE] [Sweet] [Vanilla] [Time Travel][Blowjob] [Creampie] [Lingerie] [Flexible girl] [Premature ejaculation][Multiple Orgasms] [Loving] [L-BOMB] [Tears] WARNING: [Sad/Bittersweet ending]'),
 ('The Re-population Project','[F4M] The Re-population Project [Post-Apocalyptic] [Creampie] [Impreg] [Breeding] [Strangers to lovers] [Virgin guy] [Guiding you through it]');
INSERT INTO "Downloads" VALUES (16281,'2020-09-18','23:36:47','','[F4M] A Paradise Flight.m4a','[F4M] A Paradise Flight','https://media.soundgasm.net/sounds/85ee87d9270112c25e6a43f8ad6e808a4fcb9540.m4a','https://soundgasm.net/u/replaylust/F4M-A-Paradise-Flight-1',1599760807.0,'https://www.reddit.com/r/gonewildaudio/comments/iq8kkh/f4m_a_paradise_flight_flight/','iq8kkh','[F4M] A Paradise Flight [Flight Attendant][Freeuse][Creampie][Blowjob][Cock Worship][Wet Sounds][Binaural]','/r/gonewildaudio/comments/iq8kkh/f4m_a_paradise_flight_flight/','replaylust','replaylust','gonewildaudio',NULL,0),
 (16282,'2020-09-18','23:37:19','[F4M] Do your duty as member of this house, little brother, and give me an heiress... [D&D; setting] [Drow Politics] [Incest] [Brother/Sister] [ADULTS] [FDom] [Whispers] [Manipulation] thus [RAPE] [Breeding] [Riding you] [Creampie] [You''re the only one worthy] [So fill my up womb]] [Accent]','Do your duty as member of this house, little brother, and give me an heiress....m4a','Do your duty as member of this house, little brother, and give me an heiress...','https://media.soundgasm.net/sounds/cfdf1f161e5ab2163cc731222ee2d6c842b37512.m4a','https://soundgasm.net/u/gigglechan/Do-your-duty-as-member-of-this-house-little-brother-and-give-me-an-heiress',1599946114.0,'https://www.reddit.com/r/gonewildaudio/comments/irl6jj/f4m_do_your_duty_as_member_of_this_house_little/','irl6jj','[F4M] Do your duty as member of this house, little brother, and give me an heiress... [D&D setting] [Drow Politics] [Incest] [Brother/Sister] [ADULTS] [FDom] [Whispers] [Manipulation] thus [RAPE] [Breeding] [Riding you] [Creampie] [You''re the only one worthy] [So fill my up womb]] [Accent]','/r/gonewildaudio/comments/irl6jj/f4m_do_your_duty_as_member_of_this_house_little/','giggle_chan','gigglechan','gonewildaudio',NULL,0),
 (16283,'2020-09-18','23:38:05','','[F4M] The world on my shoulders [Script Fill] [Single mom] [Stressed] [Imposter syndrome] [Tears] [Comforting].m4a','[F4M] The world on my shoulders [Script Fill] [Single mom] [Stressed] [Imposter syndrome] [Tears] [Comforting] [Hold the Moan] [Cunnilingus] [Blowjob] Gentle and Sloppy [Facefucking] [Doggy] [Cum inside me] [Co-workers to lovers] [Vanilla] [27:12]','https://media.soundgasm.net/sounds/3b540c24d8855db2771094e2e448252af3904e79.m4a','https://soundgasm.net/u/girl_in_dungarees/F4M-The-world-on-my-shoulders-Script-Fill-Single-mom-Stressed-Imposter-syndrome-Tears-Comforting-Hold-the-Moan-Cunnilingus-Blowjob-Gentle-and-Sloppy-Facefucking-Doggy-Cum-inside-me-Co-workers-to-lovers-Vanilla-2712',1600374575.0,'https://www.reddit.com/r/gonewildaudio/comments/iurpow/f4m_the_world_on_my_shoulders_script_fill_single/','iurpow','[F4M] The world on my shoulders [Script Fill] [Single mom] [Stressed] [Imposter syndrome] [Tears] [Comforting] [Kid in the next room] [Hold the Moan] [Cunnilingus] [Blowjob] Gentle and Sloppy [Facefucking] [Doggy] [Cum inside me] [Co-workers to lovers] [Vanilla] [27:12]','/r/gonewildaudio/comments/iurpow/f4m_the_world_on_my_shoulders_script_fill_single/','Girl_In_Dungarees','girl_in_dungarees','gonewildaudio',NULL,1),
 (16284,'2020-09-18','23:38:53','Sound Effects
Cars
https://freesound.org/people/Olby/sounds/77016/
Carwash
https://freesound.org/people/PerMagnusLindborg/sounds/353641/','[F4M] Bikini Car Wash [Script Fill] [Strangers to Lovers] [Striptease] [Bikini] [Missionary] [Doggystyle] [Cre.m4a','[F4M] Bikini Car Wash [Script Fill] [Strangers to Lovers] [Striptease] [Bikini] [Missionary] [Doggystyle] [Creampie] [Promo Girl] [Sir] [Sweet Tease]','https://media.soundgasm.net/sounds/66d05a650ab77078dcaefb653a5a2650c2c92800.m4a','https://soundgasm.net/u/girl_in_dungarees/F4M-Bikini-Car-Wash-Script-Fill-Strangers-to-Lovers-Striptease-Bikini-Missionary-Doggystyle-Creampie-Promo-Girl-Sir-Sweet-Tease',1599856820.0,'https://www.reddit.com/r/gonewildaudio/comments/iqytoz/f4m_bikini_car_wash_we_clean_your_ride_then_ride/','iqytoz','[F4M] Bikini Car Wash: We clean your ride then ride you! [Script Fill] [Strangers to Lovers] [Striptease] [Bikini] [Missionary] [Doggystyle] [Creampie] [Promo Girl] [Sir] [Sweet] and [Playful] with a little [Slap] when you get hand-sy too early','/r/gonewildaudio/comments/iqytoz/f4m_bikini_car_wash_we_clean_your_ride_then_ride/','Girl_In_Dungarees','girl_in_dungarees','gonewildaudio',NULL,1),
 (16285,'2020-09-18','23:39:14','You call in for a succubus to steal your soul, and a sweet, caring, but unorthodox succubus girl turns up at your door. She''s shy, but she''ll grow in confidence the more sexual energy you give her. 

(TW: DEPRESSION)','Taken Care of By A Cowgirl Succubus _18__.m4a','Taken Care of By A Cowgirl Succubus (18+)','https://media.soundgasm.net/sounds/133ed3a2ec9c9542b515579f33e1761da6259992.m4a','https://soundgasm.net/u/IvyWilde/Taken-Care-of-By-A-Cowgirl-Succubus-18',1600374310.0,'https://www.reddit.com/r/gonewildaudio/comments/iurmos/f4m_cow_girl_succubus_breastfeeds_and_comforts/','iurmos','[F4M] Cow Girl Succubus Breastfeeds and Comforts You [Gentle Fdom] [Aphrodisiac] [Breast Milk] [Nursing Handjob] [Shy to Bold] [Monster Girl] [Face Sitting] [Oral] [Reassurance] [Positivity] [Kindness] [Nerdy, Lonely Girl] [Lactation] [Cum Noises] [Big Boobs] [Hair Pulling] [Doggy Style][Corruption]','/r/gonewildaudio/comments/iurmos/f4m_cow_girl_succubus_breastfeeds_and_comforts/','Ivy_WildeVA','IvyWilde','gonewildaudio',NULL,0),
 (16287,'2020-09-18','23:40:36','','[F4M] Maid Helps You Out [Freeuse] [Blowjob] [Cock Kisses] [Begging] [Kissing] [Thigh Kisses] [Use Me For Your.m4a','[F4M] Maid Helps You Out [Freeuse] [Blowjob] [Cock Kisses] [Begging] [Kissing] [Thigh Kisses] [Use Me For Your Pleasure] [I Want To Milk Your Cum Out] [L-bombs] [Creampie]','https://media.soundgasm.net/sounds/dbd05d57f1375b4aa454f3b6cc2c08a1518ff352.m4a','https://soundgasm.net/u/littlequietthing25/F4M-Maid-Helps-You-Out-Freeuse-Blowjob-Cock-Kisses-Begging-Kissing-Thigh-Kisses-Use-Me-For-Your-Pleasure-I-Want-To-Milk-Your-Cum-Out-L-bombs-Creampie',1600300817.0,'https://www.reddit.com/r/gonewildaudio/comments/iu809e/f4m_maid_helps_you_out_freeuse_blowjob_cock/','iu809e','[F4M] Maid Helps You Out [Freeuse] [Blowjob] [Cock Kisses] [Begging] [Kissing] [Thigh Kisses] [Use Me For Your Pleasure] [I Want To Milk Your Cum Out] [L-bombs] [Creampie]','/r/gonewildaudio/comments/iu809e/f4m_maid_helps_you_out_freeuse_blowjob_cock/','littlequietthing','littlequietthing25','gonewildaudio',NULL,0),
 (16288,'2020-09-18','23:40:54','','Tomboy Lifeguard saves your life.m4a','Tomboy Lifeguard saves your life','https://media.soundgasm.net/sounds/6e801207c63dc2150c8ca3f58e4dd11d40fb398b.m4a','https://soundgasm.net/u/Javaries/Tomboy-Lifeguard-saves-your-life',1600045418.0,'https://www.reddit.com/r/gonewildaudio/comments/isatfz/f4m_tomboy_lifeguard_saves_her_best_friends_life/','isatfz','[F4M] Tomboy Lifeguard saves her best friend''s life, and now she wants to show him how much she cares [Friends to Lovers] [Beach] [Saving his life] [Blowjob] [Cowgirl] [Doggy] [Spanking] [Creampie]','/r/gonewildaudio/comments/isatfz/f4m_tomboy_lifeguard_saves_her_best_friends_life/','Javaries','Javaries','gonewildaudio',NULL,0),
 (16289,'2020-09-18','23:41:33','For as long as you can remember you’ve been tormented by a Cheshire cat. It started in school when you were young, a Cheshire cat who was the same age as you took interest in making your life miserable. At first it was just some teasing and mean jokes, but you made the mistake of reacting to her. When she liked how you reacted she became your personal tormentor. Now you feel like everything you do can lead to you seeing her. Most people fear the monster in the dark, you fear that purple cat and her evil grin.

Recently you’ve noticed things that were odd, even for her. You would wake up in the morning to find purple hairs and furs on your bed. Your dreams were of her no matter what, you had no nightmares. Sometimes when you wake up in the middle of the night you can almost feel a warmth covering that isn’t from your blanket. The feeling is so soft that it overwhelms your tired and forced you back to sleep before you can turn over to see what it is.

But something new has come up to make you even more nervous. In the eyes of the law you were now of age and the protection laws no longer applied to you. You expected to wake up one night to the Cheshire cat claiming you, but this never happened. Come to think of it no one seemed to notice. The only thing that’s different is this Cheshire no longer has her grin, rather her face is something of a nervous smile. Her words are the same, but they hold less weight. One day she appeared behind you and grabbed you from behind and the feeling was the same that you felt in your bed. You turned your head and the Cheshire cat’s face turned into one of surprise and then acceptance and then her old grin.

“Took you long enough.” She said as she chuckled.','[F4M] In the arms of a cheshire cat [monster girl] Script Fill.m4a','[F4M] In the arms of a cheshire cat [monster girl] Script Fill','https://media.soundgasm.net/sounds/22c60b5b404acb6907467ec4aaad651c5ee6326f.m4a','https://soundgasm.net/u/Sksm/F4M-In-the-arms-of-a-cheshire-cat-monster-girl-Script-Fill',1600318699.0,'https://www.reddit.com/r/gonewildaudio/comments/iucrs5/script_fill_f4m_in_the_arms_of_a_cheshire_cat/','iucrs5','[Script Fill ][F4M] In the arms of a cheshire cat [monster girl][monstergirl][cheshire cat][bully to lover][childhood friend]?[cuddles][kissing][part narrative][ear licking][L-bomb][good boy][aftercare][comforting you][gentle Fdom][had a crush on you the whole time][slight stalker][wholesome]','/r/gonewildaudio/comments/iucrs5/script_fill_f4m_in_the_arms_of_a_cheshire_cat/','pineapplecurious','Sksm','gonewildaudio',NULL,0),
 (16290,'2020-09-18','23:42:17','i love being your jack-off fantasy. it turns me on to know that when you lube up your cock and pump it hard and strong in your fist... and shoot all your sticky cum.. you''re thinking about me...


lunarhiccups','lunarhiccups _ jackoff fantasy.m4a','lunarhiccups | jackoff fantasy','https://media.soundgasm.net/sounds/48051e1f1fba56a6be1783c5210512ea0da47152.m4a','https://soundgasm.net/u/lunarhiccups/lunarhiccups-jackoff-fantasy',1599927984.0,'https://www.reddit.com/r/gonewildaudio/comments/irfmvz/f4m_script_fill_i_want_to_be_more_than_just_a/','irfmvz','[f4m] [script fill]] i want to be more than just a jack-off fantasy [tight dress teasing] [vanilla Fsub][creampie] [fantasies & dirty talk] [do whatever you want to me] [i''m here with my legs spread, whenever you need it. i''m your porn star] [soft voice] [whispers] [asmr]','/r/gonewildaudio/comments/irfmvz/f4m_script_fill_i_want_to_be_more_than_just_a/','lunarhiccups','lunarhiccups','gonewildaudio',NULL,0),
 (16291,'2020-09-18','23:42:40','written by u/ravishagirl 
performed live by u/AllusionsCollared 
Music from www.tabletopaudio.com 
[F4M][Slavegirl] [Kidnapped] [Innocence] [Prepared and Perfumed for Your Arrival] [Rape] [Pleading] [Pinned Wrists] [Helpless] [Forced Kissing] [Squirming] [Creampie] [Soft Tears] [Virgin’s Blood] [Primal] [Body Betrayal] [I''ll Be a Good Girl]','Taking Your Slave Princess_s Virginity.m4a','Taking Your Slave Princess’s Virginity','https://media.soundgasm.net/sounds/4b9b6d4c164612b544f172f6aed8afb8bc0fe960.m4a','https://soundgasm.net/u/allusions/Taking-Your-Slave-Princesss-Virginity-3',1600124596.0,'https://www.reddit.com/r/gonewildaudio/comments/iswd28/f4m_taking_your_slave_princesss_virginity_script/','iswd28','[F4M] Taking Your Slave Princess’s Virginity [Script Fill] [Slavegirl] [Kidnapped] [Innocence] [Prepared & Perfumed for You] [Rape] [Pleading] [Pinned Wrists] [Helpless][Forced Kissing] [Squirming] [Creampie] [Soft Tears][Virgin’s Blood][Primal] [Body Betrayal] [I''ll Be a Good Girl] [Performed LIVE]','/r/gonewildaudio/comments/iswd28/f4m_taking_your_slave_princesss_virginity_script/','AllusionsCollared','allusions','gonewildaudio',NULL,0),
 (16293,'2020-09-18','23:43:33','','[F4M] Fleshlight fun with your dominant girlfriend.m4a','[F4M] Fleshlight fun with your dominant girlfriend','https://media.soundgasm.net/sounds/8207b69297c1f8d19174cf5300599139b8b726d4.m4a','https://soundgasm.net/u/sleepysub98/F4M-Fleshlight-fun-with-your-dominant-girlfriend',1599953574.0,'https://www.reddit.com/r/gonewildaudio/comments/irn9p9/f4m_fleshlight_fun_with_your_dominant_teasing/','irn9p9','[F4M] Fleshlight fun with your dominant, teasing girlfriend [gentle femdom] [fleshlight] [teasing] [making you fuck your toy while i watch] [have you earned the right to fuck me?] [good boy] [creampie] [breeding]','/r/gonewildaudio/comments/irn9p9/f4m_fleshlight_fun_with_your_dominant_teasing/','sleepysub98','sleepysub98','gonewildaudio',NULL,0),
 (16294,'2020-09-18','23:43:57','A whispered ramble late at night that leaves both of us breathless. An accusation thrown at you, a playful punishment given.','[F4A] Late Night Whispers [ASMR][Whispers][Ear licking][Kissing][Moaning][Teasing][O Control][Gentle Femdom][G.m4a','[F4A] Late Night Whispers [ASMR][Whispers][Ear licking][Kissing][Moaning][Teasing][O Control][Gentle Femdom][Good Slut][Hypnotic]','https://media.soundgasm.net/sounds/7c73bb9ef05ee1d01630d1ce064c95a3d957aef5.m4a','https://soundgasm.net/u/kinkyshibby/F4A-Late-Night-Whispers-ASMRWhispersEar-lickingKissingMoaningTeasingO-ControlGentle-FemdomGood-SlutHypnotic',1599825322.0,'https://www.reddit.com/r/gonewildaudio/comments/iqp0xf/f4a_late_night_whispers_asmrwhispersear/','iqp0xf','[F4A] Late Night Whispers [ASMR][Whispers][Ear licking][Kissing][Moaning][Teasing][O Control][Gentle Femdom][Good Slut][Hypnotic][15:52]','/r/gonewildaudio/comments/iqp0xf/f4a_late_night_whispers_asmrwhispersear/','kinkyshibby','kinkyshibby','gonewildaudio',NULL,0),
 (16295,'2020-09-18','23:44:28','It''s been stressful, your friends mom comes over to make sure you''re ok, and help you de-stress','[F4M] [Script Fill] Your friend_s mom [Gentle Fdom] [MILF] [Massage] [Flirting] [Teasing] [Dirty talk] [Handjo.m4a','[F4M] [Script Fill] Your friend’s mom [Gentle Fdom] [MILF] [Massage] [Flirting] [Teasing] [Dirty talk] [Handjob] [Lube] [Titjob] [Blowjob] [CIM] [Swallowing cum] [good boys]','https://media.soundgasm.net/sounds/5ff9e04d848df54d9dbed4d8604b5fd78e876188.m4a','https://soundgasm.net/u/Sksm/F4M-Script-Fill-Your-friends-mom-Gentle-Fdom-MILF-Massage-Flirting-Teasing-Dirty-talk-Handjob-Lube-Titjob-Blowjob-CIM-Swallowing-cum-good-boys',1599872024.0,'https://www.reddit.com/r/gonewildaudio/comments/ir32bl/f4m_script_fill_your_friends_gorgeous_mom_knows/','ir32bl','[F4M] [Script fill] Your friend’s gorgeous mom knows you’ve been stressed - and relieves you in every way you need. [Gentle Fdom] [MILF] [Massage] [Flirting] [Teasing] [Dirty talk] [Handjob] [Lube] [Titjob] [Blowjob] [Sucking your stress away] [Cum in my mouth] [Swallowing cum] [LOTS of good boys]','/r/gonewildaudio/comments/ir32bl/f4m_script_fill_your_friends_gorgeous_mom_knows/','pineapplecurious','Sksm','gonewildaudio',NULL,0),
 (16296,'2020-09-18','23:45:16','Script Fill- u/elbylithiumbomb
https://pastebin.com/3aSe0LZA','Your Future Girlfriend Wants to Fuck Your Brains Out.m4a','Your Future Girlfriend Wants to Fuck Your Brains Out','https://media.soundgasm.net/sounds/345eaede4cf9aae5feaca4aa219096cc8e8963cb.m4a','https://soundgasm.net/u/Human-Armadillo-2723/Your-Future-Girlfriend-Wants-to-Fuck-Your-Brains-Out',1600205141.0,'https://www.reddit.com/r/gonewildaudio/comments/iti2cj/f4m_your_future_girlfriend_wants_to_fuck_your/','iti2cj','[F4M] Your future girlfriend wants to fuck your brains out [Script Fill] [GFE] [Sweet] [Vanilla] [Time Travel][Blowjob] [Creampie] [Lingerie] [Flexible girl] [Premature ejaculation][Multiple Orgasms] [Loving] [L-BOMB] [Tears] WARNING: [Sad/Bittersweet ending]','/r/gonewildaudio/comments/iti2cj/f4m_your_future_girlfriend_wants_to_fuck_your/','Human-Armadillo-2723','Human-Armadillo-2723','gonewildaudio',NULL,0),
 (16297,'2020-09-18','23:45:46','','The Re-population Project.m4a','The Re-population Project','https://media.soundgasm.net/sounds/5a6e61ff932945eb202d74fe667fc6c5aaed3945.m4a','https://soundgasm.net/u/singmypraise/The-Re-population-Project',1600344170.0,'https://www.reddit.com/r/gonewildaudio/comments/iui2qd/f4m_the_repopulation_project_postapocalyptic/','iui2qd','[F4M] The Re-population Project [Post-Apocalyptic] [Creampie] [Impreg] [Breeding] [Strangers to lovers] [Virgin guy] [Guiding you through it]','/r/gonewildaudio/comments/iui2qd/f4m_the_repopulation_project_postapocalyptic/','Singmypraise','singmypraise','gonewildaudio',NULL,0);
CREATE TRIGGER Downloads_au AFTER UPDATE ON Downloads BEGIN
              INSERT INTO Downloads_fts_idx(Downloads_fts_idx, rowid, title, reddit_title)
              VALUES('delete', old.id, old.title, old.reddit_title);
              INSERT INTO Downloads_fts_idx(rowid, title, reddit_title)
              VALUES (new.id, new.title, new.reddit_title);
            END;
CREATE TRIGGER Downloads_ad AFTER DELETE ON Downloads BEGIN
              INSERT INTO Downloads_fts_idx(Downloads_fts_idx, rowid, title, reddit_title)
              VALUES('delete', old.id, old.title, old.reddit_title);
            END;
CREATE TRIGGER Downloads_ai AFTER INSERT ON Downloads BEGIN
              INSERT INTO Downloads_fts_idx(rowid, title, reddit_title)
              VALUES (new.id, new.title, new.reddit_title);
            END;
COMMIT;
